apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsta-line-bot-prd
  namespace: demo-opsta-line-bot-prd
spec:
  project: demo
  sources:
  - repoURL: https://chart.onechart.dev
    chart: onechart
    targetRevision: 0.73.0
    helm:
      valueFiles:
      - $values/iac/helm-values/opsta-line-bot-prd.yaml
  - repoURL: https://github.com/opsta/opsta-line-bot.git
    targetRevision: main
    ref: values
  destination:
    name: gke-training
    namespace: demo-opsta-line-bot-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
