name: 2. Production tagging

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        required: true
        default: patch
        options:
          - patch
          - minor
          - major
        description: Choose how you are going to bump version
      skip-security-gate:
        type: boolean
        required: true
        default: false
        description: Skip security gate check

jobs:
  # SECURITY PIPELINE
  defectdojo:
    uses: opsta/.github/.github/workflows/defectdojo-security-gate.yaml@main
    if: ${{ !inputs.skip-security-gate }}
    with:
      defectdojo_product_name: ${{ github.event.repository.name }}
    secrets:
      defectdojo_host: ${{ secrets.DEFECTDOJO_HOST }}
      defectdojo_username: ${{ secrets.DEFECTDOJO_USERNAME }}
      defectdojo_password: ${{ secrets.DEFECTDOJO_PASSWORD }}

  tag:
    uses: opsta/.github/.github/workflows/tag-and-release.yaml@main
    if: ${{ !cancelled() && !failure() }}
    # SECURITY PIPELINE
    needs:
      - defectdojo
    with:
      bump: ${{ inputs.bump }}
      image_name: ${{ vars.IMAGE_NAME }}
      image_registry: ${{ vars.IMAGE_REGISTRY }}
      github_repo_name: ${{ github.repository }}
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}
