name: 2. Production tagging

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        required: true
        default: patch
        options:
          - patch
          - minor
          - major
        description: Choose how you are going to bump version
      skip-security-gate:
        type: boolean
        required: true
        default: false
        description: Skip security gate check

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ env.IMAGE_NAME }}
      image_registry: ${{ env.IMAGE_REGISTRY }}

  defectdojo:
    uses: opsta/.github/.github/workflows/defectdojo-security-gate.yaml@main
    if: ${{ !inputs.skip-security-gate }}
    with:
      defectdojo_product_name: ${{ github.event.repository.name }}
    secrets:
      defectdojo_host: ${{ secrets.DEFECTDOJO_HOST }}
      defectdojo_username: ${{ secrets.DEFECTDOJO_USERNAME }}
      defectdojo_password: ${{ secrets.DEFECTDOJO_PASSWORD }}

  tag:
    uses: opsta/.github/.github/workflows/tag-and-release.yaml@main
    if: ${{ !inputs.skip-security-gate }}
    needs:
      - setup
      - defectdojo
    with:
      bump: ${{ inputs.bump }}
      image_name: ${{ needs.setup.outputs.image_name }}
      image_registry: ${{ needs.setup.outputs.image_registry }}
      github_repo_name: ${{ github.repository }}
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}
